version: '1'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    image: redlock-web-2.0
    ports:
      - "7077:80"
    volumes:
      - .:/var/www/html


  mysql_db:
    image: mysql:latest
    container_name: redlock-web-2.0-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./redlock-db.sql:/docker-entrypoint-initdb.d/redlock-db.sql
